use std::env;
use std::error::Error;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    if let Err(error) = generate() {
        eprintln!("flutter-embedder-bindings: {error}");
        std::process::exit(1);
    }
}

fn generate() -> Result<(), Box<dyn Error>> {
    let mut arguments = env::args_os().skip(1);
    let header = PathBuf::from(arguments.next().ok_or(
        "usage: denial-flutter-embedder-bindings HEADER OUTPUT ENGINE_REVISION FLUTTER_REVISION HEADER_SHA256",
    )?);
    let output = PathBuf::from(arguments.next().ok_or("missing output path")?);
    let engine_revision = arguments
        .next()
        .ok_or("missing engine revision")?
        .into_string()
        .map_err(|_| "engine revision is not valid UTF-8")?;
    let flutter_revision = arguments
        .next()
        .ok_or("missing Flutter revision")?
        .into_string()
        .map_err(|_| "Flutter revision is not valid UTF-8")?;
    let header_sha256 = arguments
        .next()
        .ok_or("missing header SHA-256")?
        .into_string()
        .map_err(|_| "header SHA-256 is not valid UTF-8")?;
    if arguments.next().is_some() {
        return Err("unexpected extra arguments".into());
    }
    validate_hex("engine revision", &engine_revision, 40)?;
    validate_hex("Flutter revision", &flutter_revision, 40)?;
    validate_hex("header SHA-256", &header_sha256, 64)?;
    let bindings = bindgen::Builder::default()
        .header(header.to_string_lossy())
        .allowlist_function("FlutterEngine.*")
        .allowlist_type("Flutter.*")
        .allowlist_var("FLUTTER_ENGINE_VERSION")
        .derive_default(true)
        .generate_comments(false)
        .layout_tests(false)
        .raw_line("// @generated by tools/generate-flutter-embedder-bindings; do not edit.")
        .raw_line(format!("// Flutter engine revision: {engine_revision}"))
        .raw_line(format!("// Flutter source revision: {flutter_revision}"))
        .raw_line(format!("// Source embedder.h SHA-256: {header_sha256}"))
        .generate()
        .map_err(|error| format!("could not generate bindings: {error}"))?;

    bindings.write_to_file(&output)?;
    let status = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .arg(&output)
        .status()?;
    if !status.success() {
        return Err(format!("rustfmt failed with {status}").into());
    }
    Ok(())
}

fn validate_hex(label: &str, value: &str, length: usize) -> Result<(), Box<dyn Error>> {
    if value.len() != length || !value.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(format!("{label} must be exactly {length} hexadecimal characters").into());
    }
    Ok(())
}
