buildtools_path = "//flutter/buildtools"
is_debug = false
optimize_for_size = false
engine_version = "d9c0f91faefa7850131473a5c51d68950eeb40f2"
content_hash = "84f41d563f8eec342ccd5390d8c2246cf853d729"
skia_version = "5b495e3e15a59ee76af882d83316d351654c1e88"
dart_version = "b530c21f7de367b94fb04787bfed9d8e989d75e8"
full_dart_sdk = false
skia_use_libpng_decode = true
skia_use_libpng_encode = true
skia_use_rust_png_decode = false
skia_use_rust_png_encode = false
skia_use_dng_sdk = false
skia_enable_pdf = false
skia_use_x11 = false
skia_use_wuffs = true
skia_use_expat = true
skia_use_fontconfig = true
skia_use_icu = true
skia_use_xps = false
is_official_build = true
android_full_debug = false
is_clang = true
skia_enable_graphite = false
skia_enable_ganesh = false
slimpeller = true
skia_gl_standard = ""
use_clang_static_analyzer = false
enable_coverage = false
enable_lto = true
host_os = "linux"
host_cpu = "x64"
target_os = "linux"
target_cpu = "x64"
dart_target_arch = "x64"
flutter_use_fontconfig = true
dart_component_kind = "static_library"
embedder_for_target = false
dart_lib_export_symbols = false
flutter_runtime_mode = "release"
dart_version_git_info = true
dart_runtime_mode = "release"
concurrent_toolchain_jobs = 16
dart_sdk_verification_hash = "b530c21f7d"
enable_desktop_embeddings = true
enable_backtrace = true
dart_disable_secure_socket = false
use_default_linux_sysroot = true
skia_use_gl = true
skia_use_vulkan = true
skia_use_vma = false
shell_enable_vulkan = true
disable_hidden_visibility = false
flutter_prebuilt_dart_sdk = true
dart_sdk_output = "built-dart-sdk"
stripped_symbols = true
angle_enable_commit_id = false
angle_build_all = false
angle_has_astc_encoder = false
angle_enable_libdrm = false
angle_use_x11 = false
angle_use_wayland = false
angle_enable_vulkan_validation_layers = false
angle_vulkan_headers_dir =
    "//flutter/third_party/vulkan-deps/vulkan-headers/src"
angle_vulkan_loader_dir = "//flutter/third_party/vulkan-deps/vulkan-loader/src"
angle_vulkan_tools_dir = "//flutter/third_party/vulkan-deps/vulkan-tools/src"
angle_lunarg_vulkantools_dir =
    "//flutter/third_party/vulkan-deps/lunarg-vulkantools/src"
shell_enable_vulkan = false
test_enable_vulkan = false
skia_use_vulkan = false
